### ISSUE TITLE
Installing the mainline kernel is a terrible idea

### ISSUE THREAD

**Issue by flexiondotorg** [rollingrhinoremix/rhino-update#6]
I **strongly** suggest you remove the feature that installs the mainline kernel. 

🚨 This will break the expectations of Ubuntu userspace 🚨

**Comment by jbrgilbrech** [comment]
Hello, thank you for suggesting this. We are installing the mainline kernel due to this being a rolling release with the latest updates. This distro is meant to be not as stable as something as the standard or LTS variants of Ubuntu. This distro is meant for newer hardware that isn't fully supported or for people who want the latest kernels, drivers, and software packages. Thanks. 
Rhino Rolling Team

**Comment by jbrgilbrech** [comment]
If you want please contact [ubunturollingremix@gmail.com].
If you want, please suggest some other options that you would recommend.

**Comment by ajstrongdev** [comment]
I have spoken with @flexiondotorg on Discord and I do not believe he is necessarily wrong. He listed these reasons as reasons why we should not use the Ubuntu Mainline Kernel:

"The Ubuntu kernel include a loads of kernel feature enablement so the other tools work correctly, such as seccomp and AppArmor profiles and other container primitives. The Ubuntu kernels are also security patched.
The Mainline kernels are not secure and not intended for regular use. Things will break and shipping mainline kernel will undermine the credibility of the project."

I believe we should have a talk with the team ahead of release and decide on whether this is something we should pursue or not.

**Comment by ajstrongdev** [comment]
Closing for now, the development team will discuss this shortly and come to a decision.
